version: '3'

services:
  gummyjet:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/gummyjet

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=gummyjet
      - POSTGRES_PASSWORD=gummyjet
      - POSTGRES_DB=gummyjet